// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW4IzaKOzyyPxodtJabV4u6qNN5c46hl0',
    appId: '1:862073352149:web:215aa03f9b828f3030175c',
    messagingSenderId: '862073352149',
    projectId: 'fir-connection-1-c63cb',
    authDomain: 'fir-connection-1-c63cb.firebaseapp.com',
    storageBucket: 'fir-connection-1-c63cb.appspot.com',
    measurementId: 'G-6MGFD3JWF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHG6hFzY-rgstszM3_KeIYGYSi9RJPtpI',
    appId: '1:862073352149:android:53385c5845e16d4230175c',
    messagingSenderId: '862073352149',
    projectId: 'fir-connection-1-c63cb',
    storageBucket: 'fir-connection-1-c63cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ4XL9LovWEFmiO6sLvOY3m8pyN19iheI',
    appId: '1:862073352149:ios:4e26f174ac77af4930175c',
    messagingSenderId: '862073352149',
    projectId: 'fir-connection-1-c63cb',
    storageBucket: 'fir-connection-1-c63cb.appspot.com',
    iosBundleId: 'com.jurakuziyev.firebaseConnectionTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ4XL9LovWEFmiO6sLvOY3m8pyN19iheI',
    appId: '1:862073352149:ios:b796496e52bd1eff30175c',
    messagingSenderId: '862073352149',
    projectId: 'fir-connection-1-c63cb',
    storageBucket: 'fir-connection-1-c63cb.appspot.com',
    iosBundleId: 'com.jurakuziyev.firebaseConnectionTwo.RunnerTests',
  );
}
